dist: trusty
sudo: required

addons:
  apt:
    packages:
    - lftp

script:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x deploy.sh

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: ci